# -*- coding: utf-8 -*-
"""irisModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jkT08uNWiq5nfZjEyiZC9THQlU_tcAsm
"""

# Import necessary libraries
import pandas as pd # pandas is useful for data manipulation and analysis (though we use scikit-learn's built-in dataset here)
from sklearn.datasets import load_iris # This function loads the iris dataset
from sklearn.model_selection import train_test_split # To split data into training and testing sets
from sklearn.neighbors import KNeighborsClassifier # We will use the K-Nearest Neighbors algorithm
from sklearn.metrics import accuracy_score # To evaluate the model's performance

# --- 1. Load the Dataset ---
# Load the iris dataset. scikit-learn provides it as a Bunch object, which is like a dictionary.
iris = load_iris()

# The data is stored in the 'data' attribute
X = iris.data
# The target variable (species) is stored in the 'target' attribute
y = iris.target

# You can optionally convert to a pandas DataFrame for easier viewing, though not strictly necessary for this simple model
# df = pd.DataFrame(X, columns=iris.feature_names)
# df['species'] = y
# print("Dataset head:")
# print(df.head())
# print("\nSpecies names:", iris.target_names)

# --- 2. Split Data into Training and Testing Sets ---
# We split the data to train the model on one part and test its performance on unseen data.
# test_size=0.2 means 20% of the data will be used for testing, and 80% for training.
# random_state=42 ensures the split is the same every time you run the code.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"\nTraining set shape: {X_train.shape}")
print(f"Testing set shape: {X_test.shape}")

# --- 3. Choose and Train the Model ---
# We will use the K-Nearest Neighbors (KNN) classifier.
# n_neighbors=3 means the model will look at the 3 closest data points to make a prediction.
knn = KNeighborsClassifier(n_neighbors=3)

# Train the model using the training data
knn.fit(X_train, y_train)

print("\nModel training complete.")

# --- 4. Make Predictions ---
# Use the trained model to make predictions on the testing data
y_pred = knn.predict(X_test)

print("\nPredictions made on the test set.")
# print("Actual species (test set):", y_test)
# print("Predicted species (test set):", y_pred)


# --- 5. Evaluate the Model ---
# Compare the predicted species with the actual species in the test set
accuracy = accuracy_score(y_test, y_pred)

print(f"\nModel Accuracy: {accuracy:.2f}") # Print accuracy rounded to 2 decimal places

# An accuracy of 1.00 means the model predicted the species correctly for all instances in the test set.
# This is a very good score, often achievable on the Iris dataset due to its clear separation between classes.

# --- Example Prediction on New Data (Optional) ---
# You can use the trained model to predict the species of a new, unseen flower.
# Let's create a sample new flower measurement (sepal length, sepal width, petal length, petal width)
# This should be in the same format as the training data (a list of lists or a numpy array)
new_flower_measurements = [[5.1, 3.5, 1.4, 0.2]] # Example measurements (similar to a Setosa)

# Predict the species for the new flower
predicted_species_index = knn.predict(new_flower_measurements)

# Get the actual species name using the index
predicted_species_name = iris.target_names[predicted_species_index][0]

print(f"\nMeasurements: {new_flower_measurements}")
print(f"Predicted species: {predicted_species_name}")